/* 
 * Lista os índices que existem no banco
 */
SELECT INDEX_NAME,COLUMN_NAME, SQL FROM INFORMATION_SCHEMA.INDEXES WHERE TABLE_NAME = 'NFE_SAIDA_CRUA' ORDER BY INDEX_NAME,ORDINAL_POSITION;
SELECT INDEX_NAME,COLUMN_NAME, SQL FROM INFORMATION_SCHEMA.INDEXES WHERE TABLE_NAME = 'PROD' ORDER BY INDEX_NAME,ORDINAL_POSITION;



